### ISSUE TITLE
Docs: Mention that JSON parsing middleware is needed

### ISSUE THREAD

**Issue by marcelklehr** [vidigami/backbone-rest#12]
I had to find out the hard way...

**Comment by jotham** [comment]
I second this.  Took me about an hour to come and see this issue.

**Comment by kmalakoff** [comment]
We're very sorry about that. I'll update the docs. To confirm, you are talking about the JSON-quoted query parser? or just the standard JSON parser? or both?

**Comment by jotham** [comment]
I'm not sure exactly what you mean here.  I was having trouble saving objects from backbone to backbone-rest (with backbone-sql).  When an object was posted it would only return the id field (https://gist.github.com/jotham/d85591ed445a4f7910ef)  Once I changed the express program to use a json parser it resolved the issue. i.e:

```
var bodyParser = require('body-parser');

...

   app.use(bodyParser.json();
```

**Comment by kmalakoff** [comment]
@jotham thanks for clarifying what the problem was. 

I assumed that needing a json body parser for express would be self-evident, but obviously not! (I think the query parsing middleware might be less so)

I'll add this to the docs here: http://vidigami.github.io/backbone-orm/backbone-rest.html   Is that where you would expect them to be?

**Comment by jotham** [comment]
I think that would be great

**Comment by kmalakoff** [comment]
Done: http://vidigami.github.io/backbone-orm/backbone-rest.html
